apiVersion: batch/v1
kind: Job
metadata:
  name: taskapp-migration-v2
  namespace: taskapp
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: ghcr.io/ts-a-devops/taskapp-backend:latest
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: DATABASE_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: SECRET_KEY
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
