apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secret
  namespace: taskapp
type: Opaque
stringData:
  DATABASE_USER: "taskapp"
  DATABASE_PASSWORD: "taskapp_password_123"
  SECRET_KEY: "super-secret-key-change-in-production"
