[control_plane]
100.52.188.98

[workers]
13.218.143.31
44.203.51.58

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/capstone-phoenix-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
