---
- name: Base hardening on all nodes
  hosts: all
  roles:
    - base

- name: Install k3s server on control plane
  hosts: control_plane
  roles:
    - k3s_server

- name: Install k3s agents on workers
  hosts: workers
  vars:
    control_plane_ip: "10.0.1.196"
    control_plane_public_ip: "32.195.65.166"
  roles:
    - k3s_agent
